#!/bin/bash

# This script display the pdf build from different signals
# Usage: ./doit.sh signal_name

SCRIPT_DIR=$(dirname "$(realpath "$0")")
RTL_FOLDER="$SCRIPT_DIR/../../modules"
chmod +w "$SCRIPT_DIR"

rm -rf obj_dir
rm -f top.vcd

# Handle terminal arguments
if [[ $# -eq 0 ]]; then
    # If no arguments provided, use gaussian as default
    signal="gaussian"
else
    # If arguments provided, use them as input signal
    signal=("$@")
fi

DATA_FILE="${SCRIPT_DIR}/${signal}.mem"

cd $SCRIPT_DIR
name="top"

verilator   -Wall --trace \
            -cc ${RTL_FOLDER}/top.sv \
            --exe plot_tb.cpp \
            -y ${RTL_FOLDER}

# Create default empty file for data memory
touch data.hex
# Copy data from the specified file to data.hex
cp "$DATA_FILE" data.hex

# Load pdf.hex into the instruction memory as program.hex
if [ ! -f "$SCRIPT_DIR/pdf.hex" ]; then
    echo "Error: pdf.hex not found in $SCRIPT_DIR"
    exit 1
fi
cp "$SCRIPT_DIR/pdf.hex" "$SCRIPT_DIR/program.hex"

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simulation file
obj_dir/Vtop